name: hello-world-cf
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v2

      - name: SAST
        run: echo "SAST"

      - name: Doceker Image
        run: docker build -t nomoreinfo/cf-sysfoo .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/nomoreinfo/cf-sysfoo:latest'
          format: 'table'

      - name: DAST- ZAP
        run: echo "DAST ZAP"
