name: hello-world-cf
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        run: echo "Secret Scanning"

      - name: SAST
        run: echo "SAST"

      - name: Doceker Image
        run: echo "Docker Image"

      - name: Doceker Hub
        run: echo "Docker Hub"

      - name: DAST- ZAP
        run: echo "DAST ZAP"
